default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smurl_development

test:
  <<: *default
  database: smurl_test

production:
  <<: *default
  database: smurl_production
